services:
  neo4j:
    image: neo4j:4.0
    container_name: neo4j
    restart: always
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./data:/data
    environment:
      NEO4J_AUTH: neo4j/example
      NEO4J_apoc_export_file_enabled: true
      NEO4J_apoc_import_file_enabled: true
      NEO4J_apoc_import_file_use__neo4j__config: true
      NEO4JLABS_PLUGINS: '["apoc"]'

  keycloak:
    restart: always
    build:
      context: ./keycloak
      dockerfile: keycloak-Dockerfile
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    command:
      - "start-dev"

  # backend:
  #   # restart: always
  #   build:
  #     context: ./backend
  #     dockerfile: backend-Dockerfile
  #   ports:
  #     - "5000:5000"
  #   env_file:
  #     - ./backend/.env
  #   depends_on:
  #     - neo4j
  #     # - keycloak
  #   working_dir: /backend
    
  postgres:
      image: postgres
      restart: always
      # set shared memory limit when using docker-compose
      shm_size: 128mb
      # or set shared memory limit when deploy via swarm stack
      volumes:
       - type: tmpfs
         target: /dev/shm
         tmpfs:
           size: 134217728 # 128*2^20 bytes = 128Mb
      environment:
        POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8081
