version: "3.8"

services:
  neo4j:
    image: neo4j:4.0
    container_name: neo4j-apoc
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - /data:/data
      - /plugins:/plugins
    environment:
      NEO4J_apoc_export_file_enabled: "true"
      NEO4J_apoc_import_file_enabled: "true"
      NEO4J_apoc_import_file_use__neo4j__config: "true"
      NEO4J_PLUGINS: '["apoc"]'
      NEO4J_AUTH: neo4j/test1234
      NEO4J_apoc_uuid_enabled: "true"

    # command: mkdir plugins;
    #   pushd plugins;
    #   wget https://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/download/5.15.0/apoc-5.15.0-extended.jar;
    #   popd;
    #   docker run --rm -e NEO4J_AUTH=none -p 7474:7474 -v $PWD/plugins:/plugins -p 7687:7687 neo4j:5.0 ;
